language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - 10
  - 8
before_install:
  - rm .yarnrc.yml
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn set version berry
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
  - $HOME/.yarn-cache
